- name: upgrade all packages
  yum: name=* state=latest

- name: requirements packages
  yum:
    name:
      - wget
      - zip
      - gcc

- name: set timezone
  timezone:
    name: America/Lima

- name: disable sendmail
  service:
    name: sendmail
    enabled: no