- name: requirements packages
  yum:
    name:
      - nginx

- name: copy nginx config
  copy:
    src: "{{ role_path }}/files/nginx.conf"
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0755

- name: copy jenkins config
  copy:
    src: "{{ role_path }}/files/server.conf"
    dest: /etc/nginx/conf.d/server.conf
    owner: root
    group: root
    mode: 0755

- name: chkconfig nginx
  service:
    name: nginx
    enabled: yes