- name: requirements packages
  yum:
    name:
      - java-1.8.0
      - git

- name: remove the java-7
  yum:
    name: java-1.7.0-openjdk
    state: absent

- name: create user jenkins
  user:
    name: jenkins
    home: /var/lib/jenkins
    generate_ssh_key: yes
    ssh_key_bits: 2048

- name: set ownership jenkins home
  file:
    path: /var/lib/jenkins
    owner: jenkins
    group: jenkins

- name: download jenkins
  get_url:
    url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
    dest: /var/lib/jenkins/jenkins.war
    owner: jenkins
    group: jenkins
    mode: 0755

- name: create scripts directory
  file:
    path: /var/lib/jenkins/scripts
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0755

- name: copy jenkins start
  copy:
    src: "{{ role_path }}/files/jenkins.sh"
    dest: /etc/init.d/jenkins
    owner: root
    group: root
    mode: 0755

- name: copy installer plugins
  copy:
    src: "{{ role_path }}/files/installer.sh"
    dest: /var/lib/jenkins/scripts/installer.sh
    owner: jenkins
    group: jenkins
    mode: 0755

- name: copy config cloud aws for workers
  copy:
    src: "{{ role_path }}/files/ec2.groovy"
    dest: /var/lib/jenkins/scripts/ec2.groovy
    owner: jenkins
    group: jenkins
    mode: 0755

- name: copy config jenins
  copy:
    src: "{{ role_path }}/files/config.groovy"
    dest: /var/lib/jenkins/scripts/config.groovy
    owner: jenkins
    group: jenkins
    mode: 0755

- name: copy config create user
  copy:
    src: "{{ role_path }}/files/user.groovy"
    dest: /var/lib/jenkins/scripts/user.groovy
    owner: jenkins
    group: jenkins
    mode: 0755

- name: change hostname
  hostname:
    name: builds.orbis.pe

- name: update hosts file
  lineinfile:
    path: /etc/hosts
    line: '127.0.0.1 localhost localhost.localdomain builds.orbis.pe'

- name: chkconfig jenkins
  service:
    name: jenkins
    enabled: yes