---
  - hosts: all
    remote_user: ec2-user
    become: yes
    become_method: sudo

    roles:
      - { role: common, tags: ["default"] }
      - { role: volume, tags: ["default"] }
      - { role: nginx, tags: ["master"] }
      - { role: jenkins, tags: ["master"] }
      - { role: workers, tags: ["workers"] }