- name: requirements packages
  yum:
    name:
      - java-1.8.0
      - git


- name: remove the java-7
  yum:
    name: java-1.7.0-openjdk
    state: absent

- name: create user jenkins
  user:
    name: jenkins
    home: /var/lib/jenkins
    generate_ssh_key: yes
    ssh_key_bits: 2048

- name: set ownership jenkins home
  file:
    path: /var/lib/jenkins
    owner: jenkins
    group: jenkins
    mode: 0777